### ISSUE TITLE
brew is broken

### ISSUE THREAD

**Issue by cocoonkid** [erdaltsksn/random#12]
brew install erdaltsksn/tap/random
```
Error: Invalid formula: /opt/homebrew/Library/Taps/erdaltsksn/homebrew-tap/Formula/git-bump.rb
formulae require at least a URL
Error: Cannot tap erdaltsksn/tap: invalid syntax in tap!
```

**Comment by numanturle** [comment]
@cocoonkid 
can you share your mac os and brew version? if your brew version is not up to date, please try updating and then reinstalling.

**Comment by cocoonkid** [comment]
BigSour 11.14

Homebrew 3.1.9
Homebrew/homebrew-core (git revision 07324b2d0c; last commit 2021-06-05)
Homebrew/homebrew-cask (git revision d0a039f23c; last commit 2021-06-05)

Everything fresh and working. No other issues that could be related.

**Comment by numanturle** [comment]
Can you share the output of the `brew config`

**Comment by erdaltsksn** [comment]
> BigSour 11.14
> Homebrew 3.1.9
> Oh I am running on M1 arch but that shouldn't be an issue no?
> 
> Error: Cannot tap erdaltsksn/tap: invalid syntax in tap!

There shouldn't be problem with M1 arch. There was a problem with `goreleaser` file. I've fixed it at the version `v0.18.1`.

Please inform me if you still have a problem.

**Comment by cocoonkid** [comment]
Apology for late reply.

```
ORIGIN: https://github.com/Homebrew/brew
HEAD: 33e71c99dc40c0a134a236fffe2594ae6572d83c
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a27fb86b08afc7ae6dff79cf64aafb8ecc93275
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false

```

Still having this issue.

**Comment by erdaltsksn** [comment]
> Apology for late reply.
> 
> ```
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 33e71c99dc40c0a134a236fffe2594ae6572d83c
> Last commit: 11 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 2a27fb86b08afc7ae6dff79cf64aafb8ecc93275
> Core tap last commit: 3 hours ago
> Core tap branch: master
> HOMEBREW_PREFIX: /opt/homebrew
> HOMEBREW_AUTO_UPDATE_SECS: 86400
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_MAKE_JOBS: 8
> HOMEBREW_NO_ANALYTICS: set
> Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> CPU: octa-core 64-bit arm_firestorm_icestorm
> Clang: 12.0.5 build 1205
> Git: 2.32.0 => /opt/homebrew/bin/git
> Curl: 7.64.1 => /usr/bin/curl
> macOS: 11.4-arm64
> CLT: 12.5.0.22.9
> Xcode: N/A
> Rosetta 2: false
> ```
> 
> Still having this issue.

Could you try to uninstall, untap and then reinstall.

```
brew uninstall random
brew untap erdaltsksn/tap
brew install erdaltsksn/tap/random
```

Let me know you if you still have problem after these steps.

**Comment by cocoonkid** [comment]
```
❯ brew uninstall random

Error: No available formula or cask with the name "random".

❯ brew untap erdaltsksn/tap

Error: No available tap erdaltsksn/tap.


❯ brew install erdaltsksn/tap/random

==> Tapping erdaltsksn/tap
Cloning into '/opt/homebrew/Library/Taps/erdaltsksn/homebrew-tap'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (217/217), done.
remote: Total 258 (delta 139), reused 87 (delta 30), pack-reused 0
Receiving objects: 100% (258/258), 48.66 KiB | 906.00 KiB/s, done.
Resolving deltas: 100% (139/139), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/erdaltsksn/homebrew-tap/Formula/gh-label.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/erdaltsksn/homebrew-tap/Formula/random.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/erdaltsksn/homebrew-tap/Formula/git-bump.rb
formulae require at least a URL
Error: Cannot tap erdaltsksn/tap: invalid syntax in tap!

```

I did a before trying 
```
rm -rf  /opt/homebrew/Library/Taps/erdaltsksn
```
as well but no dice.

**Comment by erdaltsksn** [comment]
`https://github.com/erdaltsksn/random/releases/download/v0.18.1/random_0.18.1_darwin_amd64.tar.gz`

Could you download binary directly and test it. First, let's be sure it is working on M1 arch.

**Comment by erdaltsksn** [comment]
Fixed at: https://github.com/erdaltsksn/homebrew-tap/commit/7dda9be3e813d19eaf2152c27077cfdf6a37df51

**Comment by cocoonkid** [comment]
@erdaltsksn the binary directly works. But the brew tap is still not working. Sorry for the late reply.

**Comment by erdaltsksn** [comment]
> @erdaltsksn the binary directly works. But the brew tap is still not working. Sorry for the late reply.

Working on it.

**Comment by cocoonkid** [comment]
Works like a charm now! thanks so much!  

Now if i only would remember why I needed that in the first place a year ago  :)
